
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CRUD_Personagens2_development
test:
  <<: *default
  database: CRUD_Personagens2_test
production:
  <<: *default
  database: CRUD_Personagens2_production
  username: CRUD_Personagens2
  password: <%= ENV['CRUD_PERSONAGENS2_DATABASE_PASSWORD'] %>
